import dayjs from "dayjs";
import type { Report } from "./builder.ts";
import type { StandupConfig } from "../config/defaults.ts";
import { formatCommitMessage } from "../utils/emoji.ts";

/**
 * Render a report as a Markdown string.
 */
export function renderMarkdown(report: Report, config: StandupConfig): string {
  const lines: string[] = [];

  const dateStr = dayjs(report.date).format("dddd, MMM D YYYY");
  lines.push(`## Standup \u2014 ${dateStr}`);
  lines.push("");

  for (const repo of report.repos) {
    if (repo.error) {
      lines.push(`### ${repo.name} (error)`);
      lines.push("");
      lines.push(`> ${repo.error}`);
      lines.push("");
      continue;
    }

    if (repo.commits.length === 0) continue;

    lines.push(`### ${repo.name}`);
    lines.push("");

    // Table header
    const headers = ["Commit"];
    if (config.display.show_branch) headers.push("Branch");
    if (config.display.show_hash) headers.push("Hash");
    headers.push("Time");

    lines.push(`| ${headers.join(" | ")} |`);
    lines.push(`| ${headers.map(() => "------").join(" | ")} |`);

    for (const commit of repo.commits) {
      const msg = formatCommitMessage(commit.message, config.display.emoji);

      const cols = [msg];
      if (config.display.show_branch) cols.push(commit.branch);
      if (config.display.show_hash) cols.push(commit.shortHash);
      cols.push(dayjs(commit.date).format("HH:mm"));

      lines.push(`| ${cols.join(" | ")} |`);
    }

    lines.push("");
  }

  lines.push("---");
  const repoCount = report.repos.filter((r) => r.commits.length > 0).length;
  lines.push(
    `_${report.totalCommits} commit${report.totalCommits !== 1 ? "s" : ""} across ${repoCount} repo${repoCount !== 1 ? "s" : ""} \u00B7 Generated by standup CLI_`,
  );

  return lines.join("\n");
}
